#!/usr/bin/bash

BYTECODE="$1"
DEST_DIR="$2"

if [[ $BYTECODE == "" ]]; then
  echo "Bytecode file was not provided!"
  exit 1
fi

if [[ $DEST_DIR == "" ]]; then
  echo "Destination directory was not provided!"
  exit 1
fi

rm -rf $DEST_DIR
mkdir -p $DEST_DIR

cp $BYTECODE $DEST_DIR/main.mbc

if [ -e "mater.wasm" ]; then
  cp "mater.wasm" $DEST_DIR
fi

if [ -e "web/index.html" ]; then
  cp "web/index.html" $DEST_DIR
fi
